import { Job, BriefAnalysis, Workflow, Generation, Revision } from '@/types';

export const SEED_JOBS: Job[] = [
  {
    id: 'job-aethelgard-01',
    title: 'Aethelgard: The Obsidian Horizon Concept Film',
    clientName: 'Maison de L’Ombre (Nordic Luxury Fragrance)',
    source: 'Upwork',
    rawBrief: `Client brief pasted from Upwork:
Looking for a visionary AI Director / Studio to craft a 45-second cinematic concept teaser film for our flagship luxury fragrance launch: "Aethelgard: The Obsidian Horizon".

Visual Direction & World-building:
- High-concept brutalist sci-fi meets Scandinavian volcanic landscapes (black sand deserts, basal crystalline pillars, cold aurora borealis skies).
- Monolithic obsidian flacon rising from liquid glass. Macro droplets refracting iridescent light.
- Mood reference: Denis Villeneuve (Dune / Blade Runner 2049), ARRI Alexa 65 anamorphic widescreen feel.
- Deliverables needed:
  1) 45s Hero Teaser in 4K ProRes (16:9).
  2) 15s Vertical Cutdown (9:16) for Instagram Reels and digital ad buy.
  3) Master Keyframe prints for billboard concept art.
- Audio: Atmospheric sub-bass pulse, tactile glass whispers, and deep British narrative voiceover delivering our core manifesto: "From the ash of stillness, presence is born."
- Fixed contract budget: $4,200. Need initial preview in 7 days, final delivery in 14 days.`,
    budget: 4200,
    deadline: new Date(Date.now() + 10 * 86400000).toISOString(),
    status: 'QA',
    clientNotes: 'Client emphasized no generic CGI look; must have photorealistic physical lighting and micro camera shake.',
    referenceAssets: [
      {
        id: 'ref-1',
        name: 'Moodboard_Obsidian_Pillars.pdf',
        url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        notes: 'Volcanic basalt textures and cold mist palette.',
      },
      {
        id: 'ref-2',
        name: 'Flacon_Industrial_Design_3D_Mock.jpg',
        url: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        notes: 'Monolithic sharp-edged black perfume bottle silhouette.',
      },
    ],
    channelFeePct: 10,
    contingencyPct: 15,
    maxApprovedBudget: 65,
    approvalCheckpoints: {
      workflowApproved: true,
      workflowApprovedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      workflowApprovedBy: 'Operator (David)',
      maxBudgetApproved: true,
      maxBudgetAmount: 65,
      rightsCleared: true,
      rightsApprovedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      rightsApprovedBy: 'Operator (David)',
      finalDeliveryApproved: false, // In QA, awaiting final human sign-off
    },
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'job-crispvolt-02',
    title: 'CrispVolt: 15s Kinetic Electrolyte Energy Loop',
    clientName: 'Volt Labs Nutrition',
    source: 'Contra',
    rawBrief: `Client brief pasted from Contra message:
We need a viral, hyper-kinetic 15-second 9:16 vertical motion spot for our new CrispVolt sparkling electrolyte drink (Yuzu Citrus flavor).
- Fast rhythmic pacing: can drops into icy citrus splash, electric micro-bubbles, bold neon yellow typography flashing "SURGE RECHARGE".
- Audio needs soundalike rhythm of Daft Punk / The Weeknd fast synthwave drums.
- Client budget: $950.
- Timeline: 4 days turnaround.`,
    budget: 950,
    deadline: new Date(Date.now() + 4 * 86400000).toISOString(),
    status: 'Needs Review',
    clientNotes: 'Client wants quick turnaround, but mentioned copyrighted music style and hasn’t uploaded their official logo vector.',
    referenceAssets: [
      {
        id: 'ref-c1',
        name: 'Can_Photo_Packshot.png',
        url: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80',
        type: 'image',
        notes: 'Yuzu Yellow product can packaging.',
      },
    ],
    channelFeePct: 0,
    contingencyPct: 15,
    approvalCheckpoints: {
      workflowApproved: false,
      maxBudgetApproved: false,
      rightsCleared: false,
      finalDeliveryApproved: false,
    },
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'job-apex-03',
    title: 'Apex Kinetic: Zero-G Running Shoe Teaser',
    clientName: 'Strata Performance Gear',
    source: 'Direct Lead',
    rawBrief: `Raw inbound client email:
Hi David,
We are launching our revolutionary carbon-plate trail runner, the "Apex Strata-1". We need a 30s teaser that visualizes anti-gravity stride mechanics.
- Shots: Macro foot strike on lunar volcanic gravel, soles bending with visible carbon rebound lattice, runner sprinting through misty mountain ridge at dawn.
- Deliverables: 30s Master (16:9 4K) + 15s Cut (9:16).
- Direct budget: $2,800.
- Delivery deadline: In 2 weeks.
Can you provide the production plan, model choices, and estimated timeline?`,
    budget: 2800,
    deadline: new Date(Date.now() + 14 * 86400000).toISOString(),
    status: 'New',
    clientNotes: 'Direct corporate inquiry via portfolio contact form. Zero marketplace fees.',
    referenceAssets: [],
    channelFeePct: 0,
    contingencyPct: 15,
    approvalCheckpoints: {
      workflowApproved: false,
      maxBudgetApproved: false,
      rightsCleared: false,
      finalDeliveryApproved: false,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_ANALYSES: Record<string, BriefAnalysis> = {
  'job-aethelgard-01': {
    id: 'analysis-aethelgard',
    jobId: 'job-aethelgard-01',
    jobType: 'luxury_concept_film',
    conciseSummary: '45-second luxury fragrance teaser featuring volcanic basalt landscapes and liquid glass physics.',
    deliverables: [
      {
        id: 'del-1',
        name: 'Hero Narrative Concept Teaser',
        type: 'Hero Video',
        format: 'ProRes 422 HQ / MP4 H.265',
        resolution: '3840x2160 (4K)',
        aspectRatio: '16:9',
        durationSeconds: 45,
        targetDurationSeconds: 45,
        exactTextRequirements: ['"From the ash of stillness, presence is born."', '"Aethelgard: The Obsidian Horizon"'],
        description: 'Photorealistic multi-shot narrative sequence with Higgsfield DoP camera choreography.',
      },
      {
        id: 'del-2',
        name: 'Social Vertical Cutdown',
        type: 'Cutdown',
        format: 'MP4 H.265 (High Bitrate)',
        resolution: '1080x1920',
        aspectRatio: '9:16',
        durationSeconds: 15,
        targetDurationSeconds: 15,
        exactTextRequirements: ['"From the ash of stillness, presence is born."'],
        description: 'High-energy hook cutdown optimized for mobile feed retention.',
      },
      {
        id: 'del-3',
        name: 'Hero Keyframe Master Still',
        type: 'Keyframe',
        format: '16-bit TIFF / PNG',
        resolution: '3840x2160',
        aspectRatio: '16:9',
        durationSeconds: 0,
        targetDurationSeconds: 0,
        exactTextRequirements: ['"Aethelgard: The Obsidian Horizon"'],
        description: 'Color-graded master hero visual asset for print and key art banner usage.',
      },
    ],
    suppliedAssets: ['Basalt_Basalt_Moodboard.pdf', 'Perfume_Flacon_3D.jpg'],
    missingAssets: ['Client to provide final high-res transparent PNG for bottle typography badge.'],
    questionsForClient: ['Confirm audio mix stems delivery preference.'],
    brandConstraints: [
      'Strict luxury minimalism: cold Nordic color palette (slate, obsidian, teal, silver).',
      'Zero plastic or uncanny AI artifacts; camera must emulate Cooke anamorphic glass.',
      'Voiceover must feel authoritative, introspective, and naturalistic.',
    ],
    rightsAndConsentFlags: [
      {
        flag: 'Original Cinematic Stylistic Archetype',
        severity: 'low',
        details: 'Stylistic homage to Denis Villeneuve cinematography; no copyrighted assets or likenesses utilized.',
        approved: true,
      },
    ],
    technicalRisks: ['Temporal coherence on fluid reflections and micro-droplets.'],
    revisionRisk: 'low',
    dimensions: ['16:9 Cinema 4K (3840x2160)', '9:16 Vertical (1080x1920)'],
    durations: ['45s Hero Teaser', '15s Cutdown'],
    references: [
      'Denis Villeneuve (Dune / Blade Runner 2049) anamorphic lighting',
      'Scandinavian volcanic basalt formations & iridescent liquid glass physics',
    ],
    exactText: [
      '"From the ash of stillness, presence is born."',
      '"Aethelgard: The Obsidian Horizon"',
    ],
    rightsConcerns: [
      {
        id: 'rc-a1',
        severity: 'low',
        issue: 'Stylistic homage to Denis Villeneuve cinematography.',
        mitigation: 'Purely cinematic framing conventions; no copyrighted assets or likenesses utilized.',
        requiresApproval: false,
        approved: true,
      },
    ],
    missingInformation: [
      'Client to provide final high-res transparent PNG for bottle typography badge.',
    ],
    confidence: 96,
    decision: 'accept',
    decisionReasons: [
      'Exceptional fit for Higgsfield DoP camera control and photorealistic texturing.',
      'Client budget ($4,200) allows generous 88% gross margin even with multiple iterative passes and neural finishing.',
    ],
    proposedWorkflow: [
      { stepName: 'Hero Keyframes', capabilityNeeded: 'keyframe_generation', purpose: 'Master keyframe still' },
      { stepName: 'DoP Camera Motion', capabilityNeeded: 'camera_motion', purpose: 'Orbital camera motion' },
      { stepName: 'Video Scene Synthesis', capabilityNeeded: 'video_scene_synthesis', purpose: 'Fluid scene generation' },
      { stepName: 'Voiceover Synthesis', capabilityNeeded: 'voiceover_synthesis', purpose: 'ElevenLabs voiceover' },
      { stepName: 'Neural Master 4K', capabilityNeeded: 'neural_upscale_grade', purpose: '4K finishing and grain' },
    ],
    estimatedAttemptsByStep: {
      'Hero Keyframes': 4,
      'DoP Camera Motion': 3,
      'Video Scene Synthesis': 5,
      'Voiceover Synthesis': 2,
      'Neural Master 4K': 2,
    },
    assumptions: ['Client will provide transparent PNG logo before title card step.'],
    rationale: 'Exceptional fit for Higgsfield DoP camera control and photorealistic texturing. Client budget ($4,200) allows generous 88% gross margin even with multiple iterative generative passes and neural finishing.',
    analyzedAt: new Date(Date.now() - 3.5 * 86400000).toISOString(),
    modelUsed: 'gpt-6-astra',
  },
  'job-crispvolt-02': {
    id: 'analysis-crispvolt',
    jobId: 'job-crispvolt-02',
    jobType: 'social_video_ad',
    conciseSummary: 'Fast-paced 15-second vertical kinetic product motion spot for sparkling beverage.',
    deliverables: [
      {
        id: 'del-cv1',
        name: '15s Kinetic Vertical Social Spot',
        type: 'Social Motion Loop',
        format: 'MP4 H.265',
        resolution: '1080x1920',
        aspectRatio: '9:16',
        durationSeconds: 15,
        targetDurationSeconds: 15,
        exactTextRequirements: ['"SURGE RECHARGE"', '"CrispVolt Yuzu Citrus"'],
        description: 'Rapid-cut macro beverage splash with volumetric bubbles and bold typography.',
      },
    ],
    suppliedAssets: ['Can_Photo_Packshot.png'],
    missingAssets: [
      'Audio license clearance / explicit sign-off on synthetic original soundtrack.',
      'Vector SVG/AI brand logo asset.',
    ],
    questionsForClient: [
      'Can you approve synthetic original synthwave audio in place of Daft Punk soundalike?',
      'Can you provide vector SVG format for the CrispVolt brand mark?',
    ],
    brandConstraints: ['Neon high-energy citrus yellow and black contrast.'],
    rightsAndConsentFlags: [
      {
        flag: 'Soundalike / Copyrighted Music Imitation',
        severity: 'high',
        details: 'Client requested soundalike music matching Daft Punk / The Weeknd copyrighted masters.',
        requiresApproval: true,
        approved: false,
      },
      {
        flag: 'Exact Logo & Packaging Text Requirements',
        severity: 'medium',
        details: 'Missing brand vector logo assets; only low-res packshot provided.',
        requiresApproval: true,
        approved: false,
      },
    ],
    technicalRisks: ['High-speed fluid particle simulation.'],
    revisionRisk: 'high',
    dimensions: ['9:16 Vertical (1080x1920)'],
    durations: ['15s Hook Cut'],
    references: ['High-speed phantom camera beverage splash cinematography'],
    exactText: ['"SURGE RECHARGE"', '"CrispVolt Yuzu Citrus"'],
    rightsConcerns: [
      {
        id: 'rc-cv1',
        severity: 'high',
        issue: 'Client requested soundalike music matching Daft Punk / The Weeknd copyrighted masters.',
        mitigation: 'Explicitly reject copyrighted audio imitation. Synthesize original licensed synthwave arpeggio or request client-cleared audio stem.',
        requiresApproval: true,
        approved: false,
      },
      {
        id: 'rc-cv2',
        severity: 'medium',
        issue: 'Missing brand vector logo assets; only low-res packshot provided.',
        mitigation: 'Request vector SVG logo before initiating Neural Master 4K render.',
        requiresApproval: true,
        approved: false,
      },
    ],
    missingInformation: [
      'Audio license clearance / explicit sign-off on synthetic original soundtrack.',
      'Vector SVG/AI brand logo asset.',
    ],
    confidence: 84,
    decision: 'human_review',
    decisionReasons: [
      'Flagged for Human Review: Client requested soundalike celebrity music and lacks vector branding.',
      'Operator must resolve rights before approving workflow.',
    ],
    proposedWorkflow: [
      { stepName: 'Splash Keyframe', capabilityNeeded: 'keyframe_generation', purpose: 'High speed splash frame' },
      { stepName: 'Fluid Video Synthesis', capabilityNeeded: 'video_scene_synthesis', purpose: 'Liquid video generation' },
    ],
    estimatedAttemptsByStep: {
      'Splash Keyframe': 3,
      'Fluid Video Synthesis': 4,
    },
    assumptions: ['Client will clear original synthwave score.'],
    rationale: 'Flagged for Human Review: While budget ($950) is viable for a 15s vertical loop ($28 estimated generation cost), the client requested soundalike celebrity music and lacks vector branding. Operator must resolve rights before approving workflow.',
    analyzedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    modelUsed: 'gpt-6-astra',
  },
};

export const SEED_WORKFLOWS: Record<string, Workflow> = {
  'job-aethelgard-01': {
    id: 'wf-aethelgard',
    jobId: 'job-aethelgard-01',
    steps: [
      {
        id: 'wf-step-1',
        order: 1,
        name: 'Obsidian Monolith & Landscape Keyframes',
        stage: 'Concept & Keyframe',
        selectedModel: 'Higgsfield Concept Keyframe Pro',
        purpose: 'Establish photorealistic master visual anchor frames of basalt flacon rising from liquid glass.',
        inputs: {
          aspectRatio: '16:9',
          resolution: '3840x2160',
          lightingStyle: 'Anamorphic, chiaroscuro, volcanic mist',
          prompt: 'Monolithic black obsidian perfume bottle on wet basalt shore, subtle mist, cold morning sun, 35mm anamorphic',
        },
        expectedOutputs: '4 color-calibrated master hero keyframes.',
        estimatedAttempts: 4,
        unitCost: 0.18,
        estimatedTotalCost: 0.72,
        actualCost: 0.72,
        status: 'Completed',
        generationId: 'gen-aeth-1',
      },
      {
        id: 'wf-step-2',
        order: 2,
        name: 'Higgsfield DoP Orbital Push-In & Crane Shot',
        stage: 'Camera Motion / DoP',
        selectedModel: 'Higgsfield DoP 2.5 (Director of Photography)',
        purpose: 'Execute 360-degree orbital push-in around the flacon with mechanical steadicam smoothness.',
        inputs: {
          cameraMovement: 'Orbital arc push-in, 45-degree angle',
          focalLength: '50mm prime',
          motionSmoothing: 'Ultra',
        },
        expectedOutputs: '3 cinematic motion video plates.',
        estimatedAttempts: 3,
        unitCost: 1.60,
        estimatedTotalCost: 4.80,
        actualCost: 4.80,
        status: 'Completed',
        generationId: 'gen-aeth-2',
      },
      {
        id: 'wf-step-3',
        order: 3,
        name: 'Liquid Glass & Micro-Droplet Video Synthesis',
        stage: 'Cinematic Video Gen',
        selectedModel: 'Higgsfield Cinematic Motion V3',
        purpose: 'Synthesize iridescent liquid glass droplets running down obsidian surface with photorealistic refraction.',
        inputs: {
          fps: 24,
          coherenceWeight: 0.88,
          scenePrompts: 'Macro lens view, liquid glass condensation beads refracting aurora borealis highlights',
        },
        expectedOutputs: '5 core narrative video cuts for the 45s montage.',
        estimatedAttempts: 5,
        unitCost: 1.25,
        estimatedTotalCost: 6.25,
        actualCost: 7.50, // Real attempt took 1 extra pass
        status: 'Completed',
        generationId: 'gen-aeth-3',
      },
      {
        id: 'wf-step-4',
        order: 4,
        name: 'Cinematic Narrative Voiceover Synthesis',
        stage: 'Voice & Audio',
        selectedModel: 'ElevenLabs Voice Studio Ultra',
        purpose: 'Synthesize deep, poetic British voiceover reciting manifesto line with pristine acoustic room tone.',
        inputs: {
          voiceType: 'Deep resonant British narrative baritone',
          scriptCopy: 'From the ash of stillness, presence is born. Aethelgard.',
        },
        expectedOutputs: '24-bit 48kHz master voice stem + stereo ambient mix.',
        estimatedAttempts: 2,
        unitCost: 0.35,
        estimatedTotalCost: 0.70,
        actualCost: 0.70,
        status: 'Completed',
        generationId: 'gen-aeth-4',
      },
      {
        id: 'wf-step-5',
        order: 5,
        name: 'Neural 4K Master Upscale & Film Grain Finishing',
        stage: 'Finishing & Upscaling',
        selectedModel: 'Higgsfield Neural Master 4K & Denoise',
        purpose: 'Apply temporal de-flicker, 4K master grade, subtle Kodak 5219 35mm grain, and rec.709 color lock.',
        inputs: {
          targetResolution: '3840x2160',
          grainIntensity: 'Subtle 35mm film stock',
          colorSpace: 'Rec.709 10-bit',
        },
        expectedOutputs: 'ProRes 422 HQ 45s hero master + 9:16 vertical crop cut.',
        estimatedAttempts: 2,
        unitCost: 0.85,
        estimatedTotalCost: 1.70,
        actualCost: 1.70,
        status: 'Completed',
        generationId: 'gen-aeth-5',
      },
    ],
    totalEstimatedCost: 14.17,
    approvalStatus: 'Approved',
    approvedBy: 'Operator (David)',
    approvedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    maxApprovedSpend: 65,
    notes: 'Approved with $65 production buffer. All 5 generation steps finished successfully.',
  },
  'job-crispvolt-02': {
    id: 'wf-crispvolt',
    jobId: 'job-crispvolt-02',
    steps: [
      {
        id: 'wf-cv-step-1',
        order: 1,
        name: 'Keyframe Concept: High-Speed Beverage Splash',
        stage: 'Concept & Keyframe',
        selectedModel: 'Higgsfield Concept Keyframe Pro',
        purpose: 'Establish citrus splash lighting and can packshot hero angle.',
        inputs: {
          aspectRatio: '9:16',
          resolution: '1080x1920',
          prompt: 'Macro high-speed photography, yellow sleek beverage can exploding through sparkling water crown, micro bubbles, lime drops, volumetric lighting',
        },
        expectedOutputs: '3 vertical keyframes.',
        estimatedAttempts: 3,
        unitCost: 0.18,
        estimatedTotalCost: 0.54,
        status: 'Pending Approval',
      },
      {
        id: 'wf-cv-step-2',
        order: 2,
        name: 'High-Coherence Fluid Dynamics Video',
        stage: 'Cinematic Video Gen',
        selectedModel: 'Higgsfield Cinematic Motion V3',
        purpose: 'Generate 15-second explosive fluid simulation and can rotation.',
        inputs: {
          fps: 30,
          motionSpeed: 'Fast kinetic',
        },
        expectedOutputs: '3 vertical video clips for dynamic edit.',
        estimatedAttempts: 4,
        unitCost: 1.25,
        estimatedTotalCost: 5.00,
        status: 'Pending Approval',
      },
    ],
    totalEstimatedCost: 5.54,
    approvalStatus: 'Pending Human Approval',
    maxApprovedSpend: 25,
    notes: 'Draft workflow. Blocked until human operator resolves soundalike music rights issue.',
  },
};

export const SEED_GENERATIONS: Record<string, Generation[]> = {
  'job-aethelgard-01': [
    {
      id: 'gen-aeth-1',
      jobId: 'job-aethelgard-01',
      stepId: 'wf-step-1',
      providerRequestId: 'hg_req_77a98b41_concept',
      model: 'Higgsfield Concept Keyframe Pro',
      status: 'Completed',
      costEstimate: 0.72,
      actualCost: 0.72,
      outputUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1920&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
      outputType: 'image',
      aspectRatio: '16:9',
      meta: { resolution: '3840x2160', colorSpace: 'Rec.709' },
      startedAt: new Date(Date.now() - 2.8 * 86400000).toISOString(),
      completedAt: new Date(Date.now() - 2.8 * 86400000 + 45000).toISOString(),
    },
    {
      id: 'gen-aeth-2',
      jobId: 'job-aethelgard-01',
      stepId: 'wf-step-2',
      providerRequestId: 'hg_req_99b12a83_dop',
      model: 'Higgsfield DoP 2.5 (Director of Photography)',
      status: 'Completed',
      costEstimate: 4.80,
      actualCost: 4.80,
      outputUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      thumbnailUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=600&q=80',
      outputType: 'video',
      aspectRatio: '16:9',
      durationSeconds: 5,
      meta: { cameraRig: 'Orbital Crane Push-In', focalLength: '50mm Anamorphic' },
      startedAt: new Date(Date.now() - 2.5 * 86400000).toISOString(),
      completedAt: new Date(Date.now() - 2.5 * 86400000 + 120000).toISOString(),
    },
    {
      id: 'gen-aeth-3',
      jobId: 'job-aethelgard-01',
      stepId: 'wf-step-3',
      providerRequestId: 'hg_req_33c84f11_cinematic',
      model: 'Higgsfield Cinematic Motion V3',
      status: 'Completed',
      costEstimate: 6.25,
      actualCost: 7.50,
      outputUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
      thumbnailUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=600&q=80',
      outputType: 'video',
      aspectRatio: '16:9',
      durationSeconds: 5,
      meta: { prompt: 'Liquid glass beads cascading down obsidian flacon surface' },
      startedAt: new Date(Date.now() - 2.2 * 86400000).toISOString(),
      completedAt: new Date(Date.now() - 2.2 * 86400000 + 180000).toISOString(),
    },
    {
      id: 'gen-aeth-4',
      jobId: 'job-aethelgard-01',
      stepId: 'wf-step-4',
      providerRequestId: 'el_voice_66d11f99',
      model: 'ElevenLabs Voice Studio Ultra',
      status: 'Completed',
      costEstimate: 0.70,
      actualCost: 0.70,
      outputUrl: 'https://actions.google.com/sounds/v1/ambiences/humming_room_tone.ogg',
      thumbnailUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=600&q=80',
      outputType: 'audio',
      durationSeconds: 12,
      meta: { voiceId: 'British-Deep-Manifesto', sampleRate: '48kHz 24-bit' },
      startedAt: new Date(Date.now() - 2.0 * 86400000).toISOString(),
      completedAt: new Date(Date.now() - 2.0 * 86400000 + 20000).toISOString(),
    },
    {
      id: 'gen-aeth-5',
      jobId: 'job-aethelgard-01',
      stepId: 'wf-step-5',
      providerRequestId: 'hg_req_88e02d44_master',
      model: 'Higgsfield Neural Master 4K & Denoise',
      status: 'Completed',
      costEstimate: 1.70,
      actualCost: 1.70,
      outputUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
      thumbnailUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80',
      outputType: 'video',
      aspectRatio: '16:9',
      durationSeconds: 45,
      meta: { masterGrade: 'Kodak 5219 35mm grain', resolution: '3840x2160 UHD' },
      startedAt: new Date(Date.now() - 1.5 * 86400000).toISOString(),
      completedAt: new Date(Date.now() - 1.5 * 86400000 + 240000).toISOString(),
    },
  ],
};

export const SEED_REVISIONS: Record<string, Revision[]> = {
  'job-aethelgard-01': [
    {
      id: 'rev-aeth-1',
      jobId: 'job-aethelgard-01',
      clientNote: 'Client preview feedback: Could we make the obsidian reflection slightly colder and slow down the camera push by 15% in the opening 3 seconds?',
      affectedDeliverable: 'Hero Narrative Concept Teaser (0:00 - 0:03)',
      recommendedAction: 'Re-run Higgsfield DoP camera trajectory with ease-out logarithmic curve and decrease color temp from 4200K to 3800K.',
      expectedIncrementalCost: 1.60,
      approvalStatus: 'Approved',
      approvedAt: new Date(Date.now() - 1.8 * 86400000).toISOString(),
      createdAt: new Date(Date.now() - 2.0 * 86400000).toISOString(),
      resolvedAt: new Date(Date.now() - 1.7 * 86400000).toISOString(),
    },
  ],
};
